---
title: "R Coding Exercise"
---
#load dslabs
library(dslabs)

#observe gapmninder data
help(gapminder)

str(gapminder)
summary(gapminder)
class(gapminder)

#seperate and observe African countries
africadata<- gapminder[gapminder$continent == "Africa", ]
str(africadata)
summary(africadata)

#New object for infant mortality and life expectancy
infant_mort_and_Life_Ex <- africadata[, c("infant_mortality", "life_expectancy")]
#New object for population and life expectancy
pop_and_Life_Ex <- africadata[, c("population", "life_expectancy")]

#View infant mortality
str(infant_mort_and_Life_Ex)
summary(infant_mort_and_Life_Ex)

#View Popultaion
str(pop_and_Life_Ex)
summary(pop_and_Life_Ex)



#Create plots to view infant mortality and population compared to life expectancy
attach(africadata)
plot(infant_mortality, life_expectancy, main="infant mortality and life expectancy", xlab="Infant mortality", ylab= "life_expectancy")

attach(africadata)
plot(log, population, life_expectancy, main="Population and life expectancy", xlab="population", ylab= "life_expectancy")

#after viewing trends we see there is missing data
#Lets take a look at a specfic year, 2000
africadata_2000 <-africadata[africadata$year==2000, ]

#Now lets plot the data again
attach(africadata_2000)
plot(infant_mortality, life_expectancy, main="infant mortality and life expectancy", xlab="Infant mortality", ylab= "life_expectancy")

attach(africadata_2000)
plot(log, population, life_expectancy, main="Population and life expectancy", xlab="population", ylab= "life_expectancy")

#Lets create a linear model from the year 2000 data
fit1<-lm(life_expectancy~ infant_mortality, africadata_2000)
summary(fit1)

fit2<-lm(life_expectancy~ population, africadata_2000)
summary(fit2)

#infant mortality is a statistically significant predictor of life expectancy 
#While population was not a statistically significant predictor.
